export const allSchoolsMockData = [{
  "School Name": "Abby Kelley Foster Charter Public (District) - Abby Kelley Foster Charter Public School",
  "School Code": 4450105,
  "Subject": "ELA",
  "M+E #": 307,
  "M+E %": 42,
  "E #": 23,
  "E %": 3,
  "M #": 284,
  "M %": 39,
  "PM #": 362,
  "PM %": 50,
  "NM #": 55,
  "NM %": 8,
  "Student Included": 724,
  "Avg. Scaled Score": 496.2,
  "SGP": 55,
  "Included In SGP": 587,
  "Ach. PCTL": 36
},
{
  "School Name": "Abby Kelley Foster Charter Public (District) - Abby Kelley Foster Charter Public School",
  "School Code": 4450105,
  "Subject": "MATH",
  "M+E #": 255,
  "M+E %": 35,
  "E #": 16,
  "E %": 2,
  "M #": 239,
  "M %": 33,
  "PM #": 405,
  "PM %": 56,
  "NM #": 64,
  "NM %": 9,
  "Student Included": 724,
  "Avg. Scaled Score": 494,
  "SGP": 48,
  "Included In SGP": 587,
  "Ach. PCTL": 29
}];
